defaults:
  heading_levels: ["h2","h3"]
  keywords:
    - leadership
    - executive
    - senior leadership
    - executive team
    - board
    - board of directors
  title_variants_extra: []
  include_headings: true
  include_subheadings: true
  include_h4_in_span: true
  include_name_heading: true
  synth_name_title_line: true
  min_chars: 120
  min_confidence: 1
  window_sentences: 2
  use_css_fallback: true
  css_min_cards: 3
  use_chromote: false
  chromote_wait_ms: 2200

domains:
  "www.shn.ca":
    heading_levels: ["h1","h2","h3","h4"]
    keywords:
      - executive leadership
      - executive leadership team
      - leadership team
      - hospital leadership
      - corporate leadership
    title_variants_extra:
      - executive vice president
      - evp
      - chief strategy officer
      - cso
      - chief communications officer
      - cco
    min_chars: 40

  "www.sickkids.ca":
    heading_levels: ["h1","h2","h3","h4"]
    keywords:
      - executive team
      - leadership team
      - senior leadership
    title_variants_extra:
      - executive vice president
      - evp
      - vice president
      - vp
      - chief nursing officer
      - chief medical officer
    min_chars: 40
    use_chromote: true
    chromote_wait_ms: 2500

  "www.uhn.ca":
    heading_levels: ["h1","h2","h3","h4"]
    keywords:
      - our leaders
      - leadership team
      - executive leadership
      - senior leadership
    title_variants_extra:
      - executive vice president
      - evp
      - vice president
      - vp
    min_chars: 40
    use_chromote: true
    chromote_wait_ms: 2500

  "sunnybrook.ca":
    heading_levels: ["h1","h2"]         # include H1 so we latch onto the main section; H2 holds names
    keywords:
      - executive leadership            # match the section header
      - leadership team
      - senior leadership
    title_variants_extra:
      - executive vice president
      - executive vice-president        # hyphenated style
      - evp
      - vice president
      - vice-president                  # hyphenated style
      - vp
      - chief medical executive
      - chief nursing executive
      - chief strategy officer
      - chief communications officer
    min_chars: 40                        # don’t discard short card text
    include_name_heading: true
    synth_name_title_line: true
    include_subheadings: true
    include_h4_in_span: true
    use_css_fallback: true               # cards/grid backup
    css_min_cards: 2
    use_chromote: false                  # start without JS render; turn on later only if needed
  "quintehealth.ca":
    heading_levels: ["h1","h2","h3"]
    keywords:
      - leadership
      - executive
      - senior leadership
    title_variants_extra:
      - executive vice president
      - executive vice-president
      - evp
      - vice president
      - vice-president
      - vp
      - chief transformation officer
      - chief nursing executive
      - chief financial officer
      - chief of staff
    min_chars: 20
    include_name_heading: true
    synth_name_title_line: true
    include_subheadings: true
    include_h4_in_span: true
    use_css_fallback: true
    css_min_cards: 0
    use_list_fallback: true
    list_min_items: 2
    normalize_sequences: true      # <<< turn on the new normalizer
    use_chromote: false


